# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zUb_EKa-AYZI-XOW-aoj129hYTuohaaC
"""

!pip install ultralytics

from ultralytics import YOLO

!yolo task= detect mode= train model= yolov8n.pt data = /content/drive/MyDrive/data/data.yaml epochs=15 imgsz=640

